# Generated by Django 2.0.1 on 2018-01-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180119_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
